testing properties

diff --git a/.github/workflows/buid-and-test.yml b/.github/workflows/buid-and-test.yml
--- a/.github/workflows/buid-and-test.yml
+++ b/.github/workflows/buid-and-test.yml
@@ -11,7 +11,17 @@ on:
       - main
 
 jobs:
+  check_actor:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check actor
+        run: |
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.actor }}" != "WeiWW" ]]; then
+            echo "Only required_username can manually trigger this workflow."
+            exit 1
+          fi
   call-env-setup:
+    needs: check_actor
     uses: ./.github/workflows/env-setup.yml
     permissions:
       contents: read
@@ -19,6 +29,7 @@ jobs:
       checks: write
       pull-requests: write
   create-gpg-file:
+    needs: check_actor
     uses: ./.github/workflows/create-gpg-file.yml
     secrets:
       SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
